### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by manikantag** [dipjul/Grokking-the-Coding-Interview-Patterns-for-Coding-Questions#7]
Hi,

This is a very good initiative and finding very helpful.

Do you have any plans to continue to expand the notes of other patterns as well? I see the last update is 10 months ago. Interested in other topics as well. Thanks again.

**Comment by dipjul** [comment]
Hi @manikantag, thank you for your kind words. I’m happy to hear that you find this initiative useful.

I do have plans to continue to expand the notes of other patterns as well, but I have been busy with other projects lately. I hope to resume working on this repo soon and add more topics that interest you and other readers.

Thanks again for your interest and support. Feel free to share your feedback or suggestions anytime.
